### ISSUE TITLE
Save output of weightfield simulation

### ISSUE THREAD

**Issue by smazza** [TheRickyRoss2/Weightfield2#1]
Save the output histograms and plots of the simulation in all tabs (maybe in a single rootfile), both after "Potentials" and after "Currents". It could be nice to save the pulseshape and the gain after every event in "batch" mode to do a mean.

Thanks!
Simone

**Comment by TheRickyRoss2** [comment]
Added histogram saving using save button. All canvases and pads dumped to root files, which can be loaded through their files 
Ex:
`root potentials.root`
`root[0]> _file0->Get("potentials")->Draw()`

**Comment by TheRickyRoss2** [comment]
Added saving after each "Potentials" and "Currents" event. Weighting field, e-h pair, potentials, doping, and gain are saved to potentials.root. Currents are saved to currents.root
